#! /bin/sh

PASS='DbPa$$w0rd~~!@#(^^^%$$#JKHSKWH&*768756'

if [ ! -d "/var/lib/mysql/mysql" ]; then
	mysql_install_db
	mysqld_safe
	sleep 5

	mysql -uroot -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY '$PASS';GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost' WITH GRANT OPTION;"
	mysql -uroot -e "CREATE USER 'admin'@'%' IDENTIFIED BY '$PASS';GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;"
	mysql -uroot -e "FLUSH PRIVILEGES;"

	mysqladmin -uroot shutdown
	sleep 5
fi

/usr/sbin/mysqld